### ISSUE TITLE
Why is a BAM file needed?

### ISSUE THREAD

**Issue by pdiakumis** [zd1/telseq#24]
Hi Zhihao,

Thanks for this great tool.
Since TelSeq counts reads regardless of if they're mapped or not (based on https://github.com/zd1/telseq/issues/21), why does it require BAM files as input, instead of raw FASTQ files? Does it do any filtering based on read quality or anything?

Many thanks - Peter

**Comment by zd1** [comment]
Hi Peter, 

Thanks for your interest in telseq. Yes, you are right that mapping is not required. Ideally I should make an interface for fastq inputs. telseq uses BAM format mainly because our sequence data are mostly stored in the format, partially driven by compression etc. Teseq does not filter out reads by read quality. It does report metrics such as number of duplicates and number of mapped reads computed from a BAM, which can be informative for assessing the quality of a library. 

Best,
Zhihao
